name: Build

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Build info"
        run: echo "Trying to build on OS ${{ matrix.os }}"