name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: "Build info"
        run: echo "Trying to build on OS ${{ matrix.os }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies for build scripts
        run: pip install -r requirements.txt
      - name: Install OS specific configuration and build tree (Linux)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: | 
          sudo apt-get update
          sudo apt-get install --yes freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev \
            libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev \
            libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev
          conan config install "config/dep/conan/profiles/linux.conanprofile" -tf=profiles
          conan build . --output-folder=build --build=missing --profile:build=linux.conanprofile --profile:host=linux.conanprofile
      - name: Install OS specific configuration and build tree (Windows 2019)
        if: ${{ contains(matrix.os, 'windows') && contains(matrix.os, '2019') }}
        run: | 
          conan config install "config/dep/conan/profiles/windows2019.conanprofile" -tf=profiles
          conan build . --output-folder=build --build=missing --profile:build=windows2019.conanprofile --profile:host=windows2019.conanprofile
      - name: Install OS specific configuration and build tree (Windows 2022)
        if: ${{ contains(matrix.os, 'windows') && contains(matrix.os, '2022') }}
        run: | 
          conan config install "config/dep/conan/profiles/windows2022.conanprofile" -tf=profiles
          conan build . --output-folder=build --build=missing --profile:build=windows2022.conanprofile --profile:host=windows2022.conanprofile
