name: Build

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Build info"
        run: echo "Trying to build on OS ${{ matrix.os }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies for build scripts
        run: pip install -r requirements.txt
      - name: Install OS specific configuration and build tree (Linux)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: | 
          conan config install "config/dep/conan/profiles/linux.conanprofile" -tf=profiles
          conan install . --output-folder=build --build=missing --profile:build=linux.conanprofile --profile:host=linux.conanprofile
      - name: Install OS specific configuration and build tree (Windows)
        if: ${{ contains(matrix.os, 'windows') }}
        run: | 
          conan config install "config/dep/conan/profiles/windows.conanprofile" -tf=profiles
          conan install . --output-folder=build --build=missing --profile:build=windows.conanprofile --profile:host=windows.conanprofile
